### ISSUE TITLE
API using RedisFuture with in a "push style" throwing error 

### ISSUE THREAD

**Issue by IdanFridman** [mp911de/lettuce#169]
I am having the following error when using future and sadd:

WRONGTYPE Operation against a key holding the wrong kind of value

private RedisAsyncCommands<String, String> asyncCommands;
   asyncCommands = client.connect().async();
 RedisFuture<String> futureResult = asyncCommands.set(..)
  futureResult.thenAccept(value -> System.out.println(value));

Any idea what's wrong ?
Thanks.

**Comment by IdanFridman** [comment]
My bad. internal error insertion type.

**Comment by mp911de** [comment]
Hi @IdanFridman,

`RedisFuture.get` throws `ExecutionException`s since 4.0 when an error occured. That's different to 3.x, in which a `RedisFuture.get` returned `null` in case an execution error happened. See also [Asynchronous API (4.0) Error Handling](https://github.com/mp911de/lettuce/wiki/Asynchronous-API-%284.0%29#error-handling) in the Wiki.
