### ISSUE TITLE
performances issue using AsyncCommand

### ISSUE THREAD

**Issue by IdanFridman** [mp911de/lettuce#204]
Hi,
We are testing our app using Vertx and Redis. 
We using async connection pool of lettuce lib. 

We tried 1k concurrent users. we used profiler and that was the result:

![redis](https://cloud.githubusercontent.com/assets/4889650/13317899/4c7e09c6-dbc0-11e5-8c2d-47084a90fae6.png)

you can find our redis impl logic at: https://gist.github.com/IdanFridman/f2ef3d6ebda936dfd31e

Maybe you could give a hint why we putting some much resources on that async thread from your lib?

Thank you

**Comment by mp911de** [comment]
Hi @IdanFridman, 

not quite sure what you mean. The table shows that `AsyncCommand.await(…)` has a high self time. This is because a caller of this method tells the command to synchronize and to block the thread until the command is finished. `await(…)` is like `get(…)` a blocking method.

When using Vertx, you should avoid calls to 'await(…)' and rather use either [future chaining](https://github.com/mp911de/lettuce/wiki/Asynchronous-API-%284.0%29) or follow the [reactive API pattern](https://github.com/mp911de/lettuce/wiki/Reactive-API-%284.0%29) to not block the caller and to achieve true asynchronous behavior.

HTH, Mark

**Comment by IdanFridman** [comment]
@mp911de did you look at my gist file? I attached my code. I am using there future. please take  a look

**Comment by mp911de** [comment]
Your code uses both, the sync (`getUserSetInRadius`) and the async (`addGeoLocation`) API. The sync API internally uses the async API and performs a synchronization using `await(…)`.

The lines 

```
        client = RedisClient.create(redisUri);
        connection = client.connect();
        connection.setTimeout(10, TimeUnit.SECONDS);
        syncCommands = connection.sync();
        syncCommands.setTimeout(4, TimeUnit.SECONDS);
        geoAsyncCommand = client.connect().async();
        //  RedisClusterClient clusterClient = new RedisClusterClient(new RedisURI(REDIS_HOST,REDIS_PORT,60, TimeUnit.SECONDS));
        asyncCommands = client.connect().async();
        redisSyncConnection = client.connect().sync();
```
overwrite the timeout, setting it in one place is sufficient. The effective timeout is 4 seconds.


The improved version of your code is:

````
        client = RedisClient.create(redisUri);
        connection = client.connect();
        connection.setTimeout(4, TimeUnit.SECONDS);
        syncCommands = connection.sync();
        asyncCommands = connection.async();
        geoAsyncCommand = asyncCommands;
```
That's just a minor change but you don't require usually more than one connection.

**Comment by mp911de** [comment]
Any updates on this issue?

**Comment by IdanFridman** [comment]
will test again and notify
