### ISSUE TITLE
Implement unit test with lettuce

### ISSUE THREAD

**Issue by barmic** [mp911de/lettuce#221]
How can I create test for my code using lettuce ?
It's possible to create a pur Java RedisClient ?

Or do you know a embedded Java Redis implementation ?

Thanks

**Comment by mp911de** [comment]
Testing with a running Redis instance covers a lot of integrative aspects. You can look here: [kstyrc/embedded-redis](https://github.com/kstyrc/embedded-redis) and http://stackoverflow.com/questions/16010680/integration-testing-with-redis to get some ideas.

For plain unit tests, it's probably the best to unit-test only those classes which directly interact with the command interfaces. You can mock out these using [Mockito](http://mockito.org) or any other mocking framework. That way everything happens only in-memory, it's fast and does not require a running Redis instance at all. I would refrain from creating unit tests for `RedisClient` instances since they pollute your tests with lots of threads.

**Comment by mp911de** [comment]
Any update on this issue?

**Comment by barmic** [comment]
No thanks

**Comment by aculver28** [comment]
How are we supposed to mock the command interfaces when most of the relevant methods return a  `RedisFuture`? I've typically done something like `CompletableFuture.completedFuture(someValue);` but that doesn't appear to be something that can be done with RedisFutures.

**Comment by mp911de** [comment]
You could wrap a Command instance with AsyncCommand.
Am 29. Apr. 2019, 18:14 +0200 schrieb aculver28 <notifications@github.com>:

**Comment by aculver28** [comment]
Thanks @mp911de. Do you happen to have/know of any working examples of mocking the `RedisAsyncCommands` class without establishing a connection to a Redis host? Maybe there's something I'm missing, but it seems like even getting a value from a `Command` instance requires a `StatefulRedisConnection` instance, which is what I'm trying to avoid for purposes of unit testing.

**Comment by mp911de** [comment]
How about using Mockito?

**Comment by aculver28** [comment]
@mp911de I'm using EasyMock, but I'd run into the same issue. I'm essentially just trying to mock a `RedisAsyncCommand.type("key")` call, and trying to force it to return a specific result. I'm not seeing a good way to do that since the interface specifies a return typep of `RedisFuture` and not a `CompletionStage` or `CompletableFuture`. Just trying to see if I'm missing something obvious here.

**Comment by mp911de** [comment]
Take a look at https://github.com/lettuce-io/lettuce-core/blob/master/src/test/java/io/lettuce/core/protocol/AsyncCommandUnitTests.java. There that's Lettuce test code interacting with `AsyncCommand` which implements `RedisFuture`.

**Comment by aculver28** [comment]
@mp911de awesome. I think that's what I was looking for. I came across some similar unit tests in the spring boot project, but they weren't exactly what I needed. Somehow I missed these. Thanks!

**Comment by kell18** [comment]
Hi, 
Thanks for the support of the library! Mocking all the classes that interact with Redis is pretty brittle especially when you need to change original code. That's where fakes on deeper level comes in handy - you can use real DAO implementations in tests but with faked "driver" (like the one for JDBC for example https://github.com/kaiwinter/dummyjdbc). It'd be very nice to have it for Lettuce as well if that's possible.
