### ISSUE TITLE
Add Fire and Forget API?

### ISSUE THREAD

**Issue by CodingFabian** [mp911de/lettuce#225]
Hi Mark,
i am currently profiling an application which performs "fire and forget" writes to redis.
What I noticed is it is spending some amounts of time here;
<img width="1025" alt="screen shot 2016-04-16 at 22 21 07" src="https://cloud.githubusercontent.com/assets/176132/14583420/936cc64a-0421-11e6-95db-6b22c174c72d.png">
When looking into CommandHandler.queueCommand() I noticed that there is a if statement, checking for output of the command being null.
The code I profile uses the other code path, putting stuff into the map.
As said, this is fire and forget code, using `RedisAsyncCommandsImpl` (which is basically `AbstractRedisAsyncCommands`). I noticed that the command builder / the dispatch logic enforces an output because the future is returned.

Would it make sense to add a true "fire and forget" api, which leaves output null and returns void instead?

**Comment by CodingFabian** [comment]
For the case at hand, I decided not to use RedisAsyncCommands, but use StatefulRedisConnection directly, and then build my commands manually:
```
  executeAsync(CommandType.ZADD, commandArgs(keyBytes).add(score).add(valueBytes));

  private CommandArgs<byte[], byte[]> commandArgs(byte[] keyBytes) {
    return new CommandArgs<>(byteArrayCodec).addKey(keyBytes);
  }

  private void executeAsync(CommandType command, CommandArgs<byte[], byte[]> args) {
    redisConnection.dispatch(new AsyncCommand<>(new Command<>(command, null, args)));
  }
```

**Comment by mp911de** [comment]
Hi @CodingFabian, 
thanks for reporting the issue. The `put` is related to latency metrics collection. I worked in that area with the upcoming 4.2 version. I optimized as well some other issues related to memory allocation in `CommandArgs`. Maybe you want to give it a try, but you need to build it from the sources.

`dispatch` returns usually the same instance except when being within a transaction (`TransactionalCommand`) and when using Redis Cluster (`ClusterCommand`).

It's not necessary to wrap commands with `AsyncCommand`, just if you need a `Future`.

Leaving the output empty isn't such a good idea because of two reasons:

1. Redis needs to get rid of the response bytes, otherwise it get's an overflow, so reading the response is mandatory. That part is done by netty.
2. Because of reading the bytes, lettuce adds the read bytes to an internal buffer. This buffer never gets consumed and sooner or later you'll kill your application with out of memory.

You could use a `NullOutput` which just discards the read data. There's no `NullOutput` yet but you could implement it on your own.

**Comment by mp911de** [comment]
One more thing: Use netty 4.1 and pipelining, this will unlock some raw superpowers of ~ 25% throughput increase.

**Comment by CodingFabian** [comment]
Very nice! You say null as output is a bad idea. whoops :-)
I thought its a supported case, because the various areas of the code all check for null and seem to do something sensible.
Will add the NullOutput now.

I am also very interested in giving 4.2 a try. are you planning to release it after netty 4.1? Have you seen redis codec was merged? https://github.com/netty/netty/commit/96455a95584dd4e3bbefefb9c208e5927a8b919f

**Comment by mp911de** [comment]
Setting the output to `null` is only a good idea for a handful commands. Usually commands, which don't produce a response or just won't ever come back such as `SHUTDOWN` or `DEBUG SEGFAULT`.

I had some discussions with the netty guys and @jongyeol on https://github.com/netty/netty/pull/5001. It's a great contribution because you can really optimize code for performance using this codec. Currently I have no plan to switch to netty 4.1 because most projects stick to 4.0. lettuce if fully compatible with 4.1. I'm however considering to import the netty codec when running pre-4.1 but I need to work out how to keep code compatible.

**Comment by CodingFabian** [comment]
Ah I see you got rid of the Guava queue showing up in my profile already.

**Comment by mp911de** [comment]
Do I need to do something to complete the ticket?

**Comment by CodingFabian** [comment]
Good question, maybe i need to profile a 4.2 build to answer this. I was wondering if it makes sense to ad a whole abstraction for the idea of "nulloutput".

Maybe a valid result would be tho close this issue, saying "api stays as it is". and I can later then open a new ticket discussing memory / cpu consumption after profiling.

**Comment by mp911de** [comment]
I'll make up my mind about fire+forget. For now it works as designed and API stays as it is.
