### ISSUE TITLE
Lettuce 4.1 strange behavior when one redis node connection is temporarily cut off

### ISSUE THREAD

**Issue by long-xuan-nguyen** [mp911de/lettuce#253]
My setup:

- 20 master nodes, each responsible for 16384/20 slots
- 2 slaves for each master
- Lettuce 4.1.Final

The issue: When one of the node loses network connection (as evident in redis log where this node tries to do a sync with master after it got network connectivity back), I got a bunch of RedisCommandTimeoutException. This is fine. What happens next is that all subsequent requests to the same node now results in the same exception even when the node is now healthy. I tried to reproduce this issue locally and was able to reproduce it. Seems like CommandHandler.java now buffers the command instead of writing it out to the wire and lifeCycleState is never activated again. I do see rescheduleConnect event being fire and for the first couple of minutes, i see timeout exception connecting to that node but never got the message "reconnected successfully" and doesnt seem like channelActive() event is fired, thus causing CommandHandler to be in a bad state, always buffering commands and not send them out.

In our production environment however, what I find is that read commands to the same node are now not being assembled back in the right order to the caller. We have 500 threads sending read commands and 1 thread would get response from other thread, sometime even 2 minutes after the first one was sent out.

Any help would be greatly appreciated. What is the behavior if there is a network partition? is there a way to tell Lettuce to drop commands and not buffer, potentially not getting into this issue again and how do we configure the ConnecitonWatchDog to re-establish connections appropriately?

Make sure that:

- [x] You have read the [contribution guidelines](https://github.com/mp911de/lettuce/blob/master/.github/CONTRIBUTING.md).
- [x] You specify the lettuce version and environment so it's obvious which version is affected
- [x] You provide a reproducible test case (either descriptive of as JUnit test) if it's a bug or the expected behavior differs from the actual behavior.

**Comment by mp911de** [comment]
Thanks for the ticket. 

You asked about the behavior in case of network partitions: Lettuce remains in a working state facing the application code by default. You can [specify the behavior in a disconnected state](https://github.com/mp911de/lettuce/wiki/Client-options#disconnected-behavior) if you want to signal the application code in case a particular node connection is broken. When using a connection that is in a disconnected state because of the partition, commands will be buffered by default. When using the async API, you get the Future handle and then you can do whatever you want to do with the Future (awaiting, canceling, ...). 

By using the synchronous API, the invocation will await the result for the configured timeout (see `StatefulRedisClusterConnection.getTimeout`). If the response does not come back within the timeout, the command is canceled, and the caller receives a `RedisCommandTimeoutException`. As soon as the connection is available again, buffered commands, which were not canceled, are replayed on the connection in the order they were invoked.

When using read commands, you can control the node which is used to read from (see [Read-From Settings](https://github.com/mp911de/lettuce/wiki/ReadFrom-Settings)). The client selects a set of nodes that are qualified to read from them and performs a check which connection is healthy, so it uses active connections if at least one of the nodes is available.

The remaining/working connections can be fully used.

Please also note the reconnection uses binary exponential delays (1, 2, 4ms... up to 30 seconds). If a node is not reachable for several seconds, you may end up with a delayed reconnect up to 30 seconds. Lettuce 4.2 will provide a configurable delay.


From your description, I read you're using the synchronous API. Could you also tell me whether you have Read-From Settings configured and if you have other settings (like topology refreshing) activated?

I tried to reproduce the issue in a 2 master/2 slaves cluster but without luck. Once a master is down, the cluster responds with `CLUSTERDOWN`. Taking a slave down just causes commands to time out, once the connection is back, commands are replayed in the order they were issued to the connection.

I need your assistance to reproduce the issues as none of the issues (except the timeout) is acceptable for the client. I performed tests with disconnects lasting about 1 minute. At this stage recording the debug log and a thread dump (after the `ConnectionWatchdog` did its reconnect) would be helpful.

**Comment by long-xuan-nguyen** [comment]
I was able to reproduce on my local redis. Setup: 1 master 1 slave covering all slots

Steps:

- application is running fine calling HGET, ZCARD ...
- Put an artificial delay in the slave node; 2 minutes (debug sleep 120)
- application makes HGET calls; commands are written to the wire
- kill redis slave node
- Lettuce correctly detects channel is down
- start up redis slave node
- Lettuce is returning results out of order to the application. HGET gets PONg as the response
- Any further calls to Lettuce/Redis results in the command being bufferred and calling application eventually times out

Note that in our production environment, what I saw was that the channel was put back in activated state and commands were sent out instead of being bufferred but the responses coming back are completely out of order

Attached is the log. I've masked out our application logic but Lettuce log should be there

Would greatly appreciate your help. Our current workaround is only to monitor our service closely and restart the JVM. Note that restarting the JVM solves the issue completely so i am leaning towards an internal state in Lettuce not being maintained properly


[lettuce.txt](https://github.com/mp911de/lettuce/files/288809/lettuce.txt)

**Comment by long-xuan-nguyen** [comment]
Some more clarification: topology refresh is enabled; interval: 1 minute

Read from setting is SLAVE

**Comment by mp911de** [comment]
Thanks for the details. I think I narrowed the issue to "Ping before connect". I could reproduce the issue by enabling Ping before connect. Without enabled ping before connect it runs smoothly. The attached log file helped a lot as you enabled `TRACE` logs. The workaround would be disabling the Ping option. The main reason for Ping before connect was that lettuce didn't support SSL connections and users used `stunnel`. Because of how `stunnel` handles reconnect it was required to issue a `PING` command and await a successful response. 

This issue is not specific to Redis Cluster but affects all Redis connections.

**Comment by long-xuan-nguyen** [comment]
That was my thought as well. I can try disabling the option

However, i've been looking at CommandHandler.java, it seems like the command is added to the internal queue whenever a command is written to the transport. In the case when the command is lost in transit, wouldnt we run into the same issue? Is there any code that handles this case and pops the command out of the queue when an exception (socket, timeout, dropped connection ....) bubbles up from Netty?

**Comment by mp911de** [comment]
The reason for this behavior is the `PING` command is written to the channel on connecting and it is added to the queue, after of all other, pending commands. Redis responds with a `PONG`. `CommandHandler` takes the first element from the queue, which is a different, buffered command and so it tries to set the `PONG` response to the buffered command and not the issued `PING` command.

The command queue is only processed/cleared on a reconnect, but not on a disconnect.

**Comment by mp911de** [comment]
I deployed `4.1.3-SNAPSHOT` and `4.2.0-SNAPSHOT` to Sonatype OSS which fixes the issue. Maybe you want to give a try.

**Comment by long-xuan-nguyen** [comment]
If i am not using stunnel, is there any benefit to turn on pingBeforeActivate? I tried turning it off and it seems to work nicely

Also, how do you configure the timeout for a command? Within the connection URI? The default seems to be 1 minute

**Comment by mp911de** [comment]
You'd benefit from pingBeforeActivate if your connections are shaky and a connection has some initial state that does not match the client's view of the state. So turning it off in most cases is quite useful.

Each connection has a `StatefulConnection.setTimeout(…)` method. Timeouts are applied to the synchronous commands. If you construct `RedisClient` with a `RedisURI`, the timeout from the first `RedisURI` is set as default for all connections. The timeout is not applied to connections when using `connect(RedisURI)` methods.

**Comment by mp911de** [comment]
Implemented for 4.2.
