### ISSUE TITLE
Configure SSL certificates in runtime

### ISSUE THREAD

**Issue by maxd** [mp911de/lettuce#266]
Right not all SSL certificates should be places to *.JKS file as described [here](https://github.com/mp911de/lettuce/wiki/SSL-Connections#certificate-chainsroot-certificateself-signed-certificates) before create first SSL connection (because Java cache them as mentioned [here](http://stackoverflow.com/a/21714472/2398521)). But seems like Netty has ability to specify custom SSL certificates for different connections and make it in run-time.

So, how do you think is it possible to add settings to lettuce for configure different SSL certificates for different Redis connections?

**Comment by mp911de** [comment]
From what I see it should already be possible to change certificates in runtime when `javax.net.ssl.trustStore` is set. That's possible because each connection initializes a new `SslContext` and `javax.net.ssl.SSLEngine`. 

I plan to enhance SSL support with #249 which then would allow specifying which SSL provider to use together with a dedicated configuration to set the trust store source/password.

**Comment by mp911de** [comment]
Closing this issue as certificates can be updated while lettuce is running. The updated certificates are applied upon the next SSL connection attempt.
