### ISSUE TITLE
StatefulRedisClusterConnection.setTimeout doesn't seem to work for async commands

### ISSUE THREAD

**Issue by awiz** [mp911de/lettuce#289]
- When setting timeout to 30 milliseconds (or any value) on a connection, and using the async cluster commands interface, operations don't get timed out at the set timeout, but instead finish running. This can eventually hog all io threads (assuming there are many long working operations).
- Lettuce version: 4.1.2.Final (ubuntu 14)
- Code sample: https://gist.github.com/awiz/c003455c76bce3953e2ff0e307d13eee

**Comment by mp911de** [comment]
Thanks for your ticket. 

The timeout on a connection applies only to synchronous command execution. `Future` synchronization of commands invoked on the async API isn't affected by the timeout. `Future`s should be synchronized with a reasonable timeout inside of applications but that's up to you.

Commands that were sent to Redis but run into timeouts aren't canceled otherwise the protocol synchronization would break.

**Comment by awiz** [comment]
Hey

Thanks for the quick response

What would be the expected behavior in case of a server hanging? I mean for example when we asynchronously send an mset command, and the server at that time is suffering - will the client deplete its io threads and block?

Is there a socket level timeout in that case?

Thanks
Avi

**Comment by mp911de** [comment]
Not all is lost when the server is hanging. Synchronizing with reasonable timeouts is one way how to protect your application and all upstream clients. Not sure why Redis should hang because of `MSET`. If Redis hangs, then something is fishy on the Redis side. You could also disconnect from Redis but TBH, if Redis hands you run into a different kind of problems and timeouts are just protection but not a solution.

By 

> socket level timeout

you mean the `SO_TIMEOUT` or read timeout? 

lettuce uses non-blocking NIO, so there's no such thing as read timeout on socket-level in the first place. It might be possible to introduce general read timeouts (from the command sent time to command completion or from a first byte read time for a particular response), but that again can screw up the protocol. Commands sent to Redis are in an unknown processing state until Redis comes back with an answer. Such commands can get executed but how would you know if running into timeouts?

**Comment by awiz** [comment]
Hey

I guess my example wasn't a very good one.

A more relevant (for me) scenario, would be a client that is used for reading data, and at a high rate.

In case some of the requests are being served more slowly than the others (for what ever reason - there can be several), I'd like to be able to fail fast on these requests, and not have the IO threads that are working on processing the slow queries get stuck for a long time. 

I can add a watchdog on the RedisFuture, and stop waiting on it after X milliseconds, but that only helps w.r.t. application threads, while the IO threads are still stuck on long read operations.

Is it possible to allow canceling RedisFutures which are performing read operations (assuming these don't have side effects on Redis)?

**Comment by mp911de** [comment]
Redis is single-threaded which means all requests are served sequentially. It does not matter whether a client uses one or multiple connections. Awaiting a `Future` for a given timeout is general a good idea and would suit your scenario as the waiting thread gets unblocked. 

Canceling a future has no impact on the Redis communication in the first place. Canceling affects only retries (i.e. a connection gets disconnected and canceled commands aren't retried whereas non-canceled commands are re-submitted). A canceled command also notifies it's subscribers (callers of `get()`) to throw a `CancelationException`.

I/O threads are always busy (or not) with I/O. There's no chance (except disconnect) of unbinding the EventLoop threads from I/O. Netty's I/O threads aren't really an issue as I/O is non-blocking. Each thread is responsible for zero to many channels. So If a command gets stuck but there's no network I/O the I/O threads aren't busy with that particular connection.

**Comment by awiz** [comment]
OK

In that case, I'll use the application level timeouts and test it.
 
Thanks again for the quick response. 
Avi

**Comment by mp911de** [comment]
You're welcome. May I close this ticket or is there anything else I can assist you with?

**Comment by awiz** [comment]
Closing it :)

**Comment by awiz** [comment]
Sorry, I'll close it :)

On Sun, Jun 26, 2016 at 5:04 PM, Mark Paluch <notifications@github.com>
wrote:

> You're welcome. May I close this ticket or is there anything else I can
> assist you with?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mp911de/lettuce/issues/289#issuecomment-228603043>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASSw6VgolydqMXglfBPIemevZGvlBYlAks5qPocJgaJpZM4I-hMf>
> .
>



-- 
Avi Zohary
Software Engineer, Paid Recs, Israel
azohary@outbrain.com
| o: 077.270.6651 | m: 054.455.1574
<http://www.outbrain.com/?utm_source=gmail&utm_medium=email&utm_campaign=email_signature>

-- 
The above terms reflect a potential business arrangement, are provided solely 
as a basis for further discussion, and are not intended to be and do not 
constitute a legally binding obligation. No legally binding obligations will 
be created, implied, or inferred until an agreement in final form is executed 
in writing by all parties involved.

This email and any attachments hereto may be confidential or privileged. 
 If you received this communication by mistake, please don't forward it to 
anyone else, please erase all copies and attachments, and please let me 
know that it has gone to the wrong person. Thanks.
