### ISSUE TITLE
Tests don't run against specified redis version

### ISSUE THREAD

**Issue by thepeterstone** [mp911de/lettuce#293]
The `make test` target clones the "unstable" branch of redis and runs against that, instead of the version specified as "tested" in the README.

Tested lettuce version: **4.0.Final**
Redis server **v=3.0.3 sha=00000000:0 malloc=libc bits=64 build=a23062e8b695b71a**

Version 4.0.Final says "This version of lettuce has been tested against Redis 3.0.", yet includes tests that don't work against Redis prior to 3.2.0. The `make test` target fails against the unstable branch that it's trying to clone, and if you provide Redis version 3.0 locally, the tests assert on Redis commands that don't appear until 3.2.0, such as GEOADD, or behavior that was different before 3.2.0, such as RENAMENX.

Repro:
```
git clone https://github.com/mp911de/lettuce.git --branch 4.0.Final --single-branch
cd lettuce
make prepare ssl-keys test
```

(You can repro against an existing install of redis-server by commenting out the section of the Makefile that downloads redis.)

I think the Makefile should pin a particular tag of the Redis repo, rather than tracking against the unstable branch.

**Comment by mp911de** [comment]
Thanks for your ticket. That's true, the docs of lettuce 4.0 said it's tested against Redis 3.0. To be exact: It was tested against 3.0 but the wording doesn't express anything about the outcome of the tests. The current readme mentions 3.2 RC3 and the release notes `It is tested continuously against the latest Redis source-build`. The current state is that lettuce is always built against Redis `unstable` which can always introduce build failures because of an unstable Redis version but also reveals things which are changed or removed during development.

Building lettuce against a tag requires Redis releases and pinning lettuce to Redis releases means that Redis snapshot features can no longer be tested which is a no-go. lettuce keeps up development aside of the Redis progress (see #267 and #270). Another issue in Redis development is, there are not always RC or beta releases (see `3.2.1` which introduced the `TOUCH` command). So the currently only consistent way is using `unstable` and pinning the `Makefile` right before the release to the commit sha.

**Comment by thepeterstone** [comment]
Thanks for the response. This came up because RedisLabs is running version 3.0.3, and we're running into a DNS caching bug, but updating to the current version of lettuce (while fixing that bug) causes some other problems, so I was hoping to backport the fix until we can work out a smooth upgrade path.

It would be awesome if there were a way to test against the version that RedisLabs is using in production, but I understand that that makes the dev process more complicated. I'd love it if it were more obvious that "tested against" doesn't imply "works with" :-)

**Comment by mp911de** [comment]
Thanks for your feedback. I'll consider it for the upcoming release. Could you tell me about the issues you're running into when updating to lettuce 4.2.0? Lettuce 4.2.0 provides a DNS lookup interface to mitigate DNS caching issues.

**Comment by thepeterstone** [comment]
Sure - I'll try to get together a repro for you. Right now my working copy isn't in a good state to do that but once I've worked around this I can start over.

Thanks!

**Comment by thepeterstone** [comment]
Hi Mark - I'll open another issue for the problems we're seeing upgrading lettuce. It's a little difficult to minimize to a reasonable test case and seems to be environment-specific. Thanks for your help understanding this issue.
