### ISSUE TITLE
Issue with channel publish when pipelining commands

### ISSUE THREAD

**Issue by tusharm** [mp911de/lettuce#348]
Lettuce: 4.1.2.Final
Java: 1.8.0_25

Hi,

I am using Lettuce to fire multiple pipelined commands, one of which is a channel publish. Specifically, I want to publish to the channel only when it is active. Here is a testcase: https://gist.github.com/tusharm/05ac8dd454f09bd0ec89ef1eeb74b1b5. I notice when there are no subscribers to the channel, the test passes. However it hangs (and keeps running forever) when there are one or more subscribers. 

I suspect the  event loop is getting blocked somehow, though not sure how.  Is there something obviously wrong here?

Tx

**Comment by mp911de** [comment]
Hi @tusharm 

that's all correct and also you're right with your analysis. Connections in Redis can enter different states and the states define what's possible and what's not possible. When entering Pub/Sub mode with `PSUBSCRIBE`/`SUBSCRIBE`, you're only allowed to issue `PSUBSCRIBE`/`SUBSCRIBE`/`PUNSUBSCRIBE`/`UNSUBSCRIBE` commands.

<img width="371" alt="screenshot 2016-08-31 08 35 31" src="https://cloud.githubusercontent.com/assets/1035015/18118551/e879e344-6f55-11e6-97cf-fa2c3de6d9d5.png">

If you want to use Redis Pub/Sub and other Redis Commands then you need to maintain two independent connections inside your application. The one to receive Pub/Sub notifications and the other one for working with Redis data structures.

**Comment by tusharm** [comment]
Hey, thanks for getting back on this so quick.

I was aware that I needed separate connections for a publish and a subscribe. Note however that my test case is not subscribing to any channel; it just publishes. As far as I understand, I could still use a single connection to do a publish and a, say, zadd. Is that not correct?

**Comment by mp911de** [comment]
Sorry, I missed that point, and somehow I failed at reading your question in the first place. My bad. 

That's correct, in that case, you can use that connection. The reason why the connection hangs (I should have tried it first) is that you invoke a command on completion while `AutoFlush` is disabled. Calling [`flushCommands`](https://gist.github.com/tusharm/05ac8dd454f09bd0ec89ef1eeb74b1b5#file-redistest-java-L50) will flush the initial batch of commands. At that time the `pubsubChannels` is flushed (written to the channel) and as soon as that command completes it invokes [`publish`](https://gist.github.com/tusharm/05ac8dd454f09bd0ec89ef1eeb74b1b5#file-redistest-java-L47). The connection is still in `AutoFlush = false` mode which leads to a queued command but that command is never written to the channel.

I'd propose to keep `AutoFlush` disabling out of the game right now. It's an optimization if you want to improve throughput for batch writing. Issuing command sequences with mixing conditional logic will lead to cases like this where you block your whole application.

I noticed one more thing. Although you're on the right approach you might want to notice that commands are completed on the I/O event loop. You can invoke non-blocking actions (command chaining) but you should not block the event loop otherwise the command completion is blocked which blocks channel I/O processing and you again lock up your system.

**Comment by tusharm** [comment]
Thanks @mp911de for your inputs!

This is a high throughput realtime service that pushes ~5K messages/sec (~4Mbps) to both the  sorted set and the channel and needs to do it in sub-second range. Pipelining gave it a significant perf boost; I was hoping pushing only to active channels will further reduce the overall latency. If I'll ever be able to use only one of those two, I guess I'll have to rethink my design. Are there other options?

About blocking the event loop, I'm assuming you mean the `CompletableFuture.allOf(..).get()` call. The reason behind this is I have to completely push this batch to Redis, before I pick up the next one.

**Comment by mp911de** [comment]
You get at least 10Kops/sec/Thread out of the box (on a reasonable machine) if triggered asynchronously. Firing commands one-by-one with intermediate synchronization gives you less throughput. Lettuce uses pipelining out of the box, it does not wait with I/O until the previous command is completed but writes commands from different threads directly to the channel.

Command batching is only useful if you want to push performance from 100Kops to 1Mops/sec. 

Redis processes commands in sequential order. The last command you send is processed last and it's guaranteed the previous command is completed before the last one. This provides the property that you can rely/synchronize on the last command.

You're not blocking the event loop in your code because you're just triggering a command without awaiting its synchronization. So that approach works for you.

**Comment by tusharm** [comment]
Hi,

I have ~200 threads spread across 4 EC2 instances talking to an Elasticache instance. Elasticache metrics show me ~500K cmds/sec, which implies I am not doing more than 2.5K cmd/sec from each thread. I am doing a fair bit of pre-processing before the actual Redis push; that might explain the low throughput. Note that CPU util on each EC2 instance is ~20%, while Elasticache is close to 85%. 

Just trying out several things, one of which is:
```
try (RedisAsyncCommands<String, String> async = redisClient.connect().async()) {
            // we want to get the list of active channels first; then we start pipelining
            async.pubsubChannels(channelName).thenCompose(channels -> {
                //set up pipelining
                async.setAutoFlushCommands(false);
                
                Double now = valueOf(now().toEpochMilli());
                String testMessage = "{\"message\":\"all good\"}";
                Future<?> publish = completedFuture(0L);
                if (!channels.isEmpty()) {
                    publish = async.publish(channelName, testMessage);
                }

                async.flushCommands();
                async.setAutoFlushCommands(true);
            })
        }
``` 
So, I query for active channels first and then start pipelining. This avoids the conditional future chaining. What are your thoughts on this?

Thx

**Comment by mp911de** [comment]
Dealing with `setAutoFlushCommands` might require dedicated connections - that's what you did here. I'd argue that connecting on demand is more expensive than sharing one connection and just using it. If you're running that code as a performance test, it would be worth of trying it that way. What do you think?

**Comment by tusharm** [comment]
I have this change deployed in a staging env now and it looks good at the moment. Same load as I said earlier + ~0.3 secs batch processing time.  I'll monitor this for a while and keep you updated.

**Comment by mp911de** [comment]
Any update on this issue?

**Comment by tusharm** [comment]
Hey, I ran with the change in staging env without any issues. 

Just to avoid checking for active channels on every batch request, I switched to computing active channels asynchronously; essentially polling for active channels every n secs in a separate thread.

**Comment by mp911de** [comment]
Thanks for your response. May I close this ticket or is there anything else I can assist you with?

**Comment by tusharm** [comment]
Thanks for your help @mp911de! Let's close the ticket.
