### ISSUE TITLE
Async command emit during cluster failover doesn't have complete signal.

### ISSUE THREAD

**Issue by kojilin** [mp911de/lettuce#356]
lettuce 4.2.0 & 4.2.2 
I have a cluster 3 master + 3 slave.
My testing gist is like this https://gist.github.com/kojilin/cb19d9fb65fabaeab925096d17278a14
If I shutdown 1 master, the thread will stop at https://gist.github.com/kojilin/cb19d9fb65fabaeab925096d17278a14#file-main2-java-L37
Is there any possibility to trigger failed signal to RedisFuture.

Make sure that:

- [x] You have read the [contribution guidelines](https://github.com/mp911de/lettuce/blob/master/.github/CONTRIBUTING.md).
- [x] You specify the lettuce version and environment so it's obvious which version is affected
- [x] You provide a reproducible test case (either descriptive of as JUnit test) if it's a bug or the expected behavior differs from the actual behavior.

**Comment by mp911de** [comment]
Hi, 
you're using the async API with lettuce defaults. The async API never times out using `get()` but you're responsible for providing timeouts on each call (`get(timeout, timeunit)`). The default timeout is only applied to the sync API where users don't have the freedom to specify timeouts on a per-operation basis.

The other thing is, lettuce auto-reconnects by default in the background. Commands are queued and replayed once the server is back. You can control the buffer size and the disconnected behavior using [client options](https://github.com/mp911de/lettuce/wiki/Client-options#request-queue-size).

`RedisClusterClient` has one specialty regarding disconnection: Redis Cluster requires multiple connections because of multiple hosts. It is possible to work with a Cluster connection while one node is down and other nodes are still up.

**Comment by kojilin** [comment]
2. Thanks, I didn't notice after recover, thats help me too.

Because I'm highly depends on future.then(...), so for me I want to have way to control, like currently I'm using guava like solution.
```
Futures.withTimeout(connect.async().get(key), 3, TimeUnit.SECONDS, executorService);
```

Didn't notice the queue's implementation, so curious that why no failure signal.
Looks like this not a problem, thanks.

**Comment by mp911de** [comment]
I think you can apply the timeout on the last element in your chain which makes your code a bit more simple.
