### ISSUE TITLE
Many commands will failed when cluster topology change

### ISSUE THREAD

**Issue by xkai08** [mp911de/lettuce#462]
hi mp911de:
 I'm using lettuce 4.3.0Final in redis cluster,my cluster has 3 masters and 3 slaves.When I kill one of master,the slave will be the new master.
however, client.connect().sync().keys("*") will throws exception:com.lambdaworks.redis.RedisConnectionException: Unable to connect to /192.168.137.133:6372
Not only this command,like all(),masters()...
this is "cluster nodes" returnd info:
192.168.137.133:6376 master - 0 1486197867917 16 connected 10923-16383
192.168.137.133:6373 slave  0 1486197868921 16 connected
192.168.137.133:6375 master - 0 1486197867413 17 connected 5461-10922
192.168.137.133:6374 slave  0 1486197866909 4 connected
192.168.137.133:6372 master,fail - 1486175111897 1486175110092 2 disconnected
192.168.137.133:6371 myself,master - 0 0 1 connected 0-5460

**Comment by xkai08** [comment]
client.connect().sync().all().asMap() will throw exception

**Comment by xkai08** [comment]
maybe all cross hosts commands have this issue

**Comment by xkai08** [comment]
my redis version is 3.2.7

**Comment by mp911de** [comment]
Hi, that's the desired behavior. 
Lettuce connects on demand to cluster nodes and the node selection requires working connections to execute commands on multiple nodes. Some commands on the Cluster API are implemented to take multiple hosts into account, like `keys()`.

What's your expectation regarding the behavior?

**Comment by xkai08** [comment]
Yes.
`10.16.74.16:6383> cluster info
cluster_state:ok
cluster_slots_assigned:16384
cluster_slots_ok:16384
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:9
cluster_size:3
cluster_current_epoch:13
cluster_my_epoch:10
cluster_stats_messages_sent:19510078
cluster_stats_messages_received:17983524
`
my cluster_size is 3 and cluster_state is ok,but cluster nodes return 4 masters. I think the master should be avoid which flag is FAIL

**Comment by mp911de** [comment]
Sliently skipping a node might affect your application in a negative way. In your case, if asking for all keys, you just get keys from 3 instead of 4 nodes. If the data, you were looking for was stored on the failed node, it would look like as if the data was never stored. Outages in a distributed system are to be expected and handled accordingly.

The API provides a way for you to select nodes individually, take a look at [RedisAdvancedClusterAsyncCommands.nodes(Predicate<RedisClusterNode>)](http://redis.paluch.biz/docs/api/releases/latest/com/lambdaworks/redis/cluster/api/async/RedisAdvancedClusterAsyncCommands.html#nodes-java.util.function.Predicate-). You can filter non-available nodes yourself, if that's a requirement for your application.

**Comment by xkai08** [comment]
In a redis cluster,the slave primary effect is high availability(HA).If my app used these api in somewhere and the master has been moved.The app will don't work right until the down node restore.But in fact,the cluster is right.If I use `nodes(Predicate)` ,I must merge result by myself. These advanced apis will lose theirs significance in redis cluster.
Redis cluster has a config `cluster-require-full-coverage`,default value is yes. If any master down and don't have slave become to new master.These api like `keys` will failed.It doesn't return wrong results that lose some keys.
We can get the cluster's size and master's size. If live master's size equals cluster's size,cluster status always right. Excluding master that flag is `FAIL` does't affect result.

**Comment by xkai08** [comment]
In other words,if I used api like `keys` .I couldn't shutdown any machine to do maintaining.But it is impossible.

**Comment by mp911de** [comment]
You're right saying when a master is down and no new master is elected yet, then that kind of calls will fail.

On a different note, you should not use `KEYS` to enumerate keys in a production system but rather `SCAN`. `SCAN` is implemented on the cluster client (since 4.2) to select nodes (according to `ReadFrom`) and to iterate over the node set while iterating over keys.

**Comment by xkai08** [comment]
Yes,you are right.`keys` is just a example. I found this problem when I used `scriptLoad`. This command select a random master to load script.My script couldn't find key sometimes.So,I found this problem when I use `master` to load script on all masters.I finally used `nodes` to resolve this problem.
I have some suggestion

1. add a api like `scriptLoad(String script,String key)`  to load script on specified node
2. add a api like `master(boolean skipUnreachable)`,`slave(boolean skipUnreachable)`,`all(boolean skipUnreachable)`

The end.Thank you for help me.Thank you for read my Chinese English.
:-)

**Comment by mp911de** [comment]
`scriptLoad` is executed, like the most other key-less commands, on the default connection node. That can be any master or slave node. 

Keep in mind that connections to cluster nodes are held open once they were established. There are three states that can occur with the NodeSelection API:

1. All servers reachable (all good then)
2. A node is attempted to connect but it's down: You run into an exception (that's the case you described)
3. An existing connection is down and you attempt to execute a command: If the connection is re-established in time, then the command is executed with some delay. Otherwise, it runs into a timeout. You can still trigger commands but their outcome depends on when the connection is re-connected.

Therefore, it's not possible in the first place to skip nodes that are down. However, I think that could be a common case that a node is down and you might be interested in skipping that node. If the topology is updated, then you can fall back to custom predicates.

One additional thought regarding maintenance: While you have a cluster of multiple nodes, it's not a good practice to take a node offline without changing the topology configuration in Redis.

**Comment by xkai08** [comment]
Ok. I understand.Thank you a lot.

**Comment by ldwnt** [comment]
> `scriptLoad` is executed, like the most other key-less commands, on the default connection node. That can be any master or slave node.
> 
> Keep in mind that connections to cluster nodes are held open once they were established. There are three states that can occur with the NodeSelection API:
> 
> 1. All servers reachable (all good then)
> 2. A node is attempted to connect but it's down: You run into an exception (that's the case you described)
> 3. An existing connection is down and you attempt to execute a command: If the connection is re-established in time, then the command is executed with some delay. Otherwise, it runs into a timeout. You can still trigger commands but their outcome depends on when the connection is re-connected.
> 
> Therefore, it's not possible in the first place to skip nodes that are down. However, I think that could be a common case that a node is down and you might be interested in skipping that node. If the topology is updated, then you can fall back to custom predicates.
> 
> One additional thought regarding maintenance: While you have a cluster of multiple nodes, it's not a good practice to take a node offline without changing the topology configuration in Redis.
(A

What about this scenario:

I have a cluster of N masters and N*M slaves. At some moment, 1 machine is down with 1 master (A) and K slaves. The whole system is supposed to keep working becuase a former slave of A becomes the new master and the cluster is OK again. This situation requires no emergency fix at mid night and the IT staff just need to fix the machine, start it with the redis nodes the other day.

However, if redis clients keep calling the down master A, many requests fail until A is manually removed from the cluster. This is painful for both maintetance staff and end users.

**Comment by mp911de** [comment]
Make sure to enable topology refresh via `ClusterClientOptions`.
