### ISSUE TITLE
To get the thread pool status

### ISSUE THREAD

**Issue by ameenhere** [mp911de/lettuce#492]
This is a question. I am working with Azure Redis Cache (Premium Tier-6GB Size) and have integrated our spring application using lettuce 3.5 ( for Java 7). 
We are not using any blocking commands and are limited to only get,set,setex,expire and del commands. Hence we have not implemented any connection pooling.  We are using an unclustered redis server with the ssl port (6380).

As part of our performance test on the application, we find out in some cases commands take 500ms or in rare scenarios even 1 second to complete. (This is using stopwatch around the lettuce method call and not using the latency util). We are currently thinking of setting a higher ioThreadPoolSize/computationThreadPoolSize. 

1) What do you think is an optimal setting for the threadpool size for a production environment?
2) Is there a way to log the thread pool status in terms of the active/busy/waiting threads?
3)Do you think there will be a difference in latency if we connect to the non-ssl port?

**Comment by mp911de** [comment]
There are a couple of things you could do:

1. Enable latency metrics (see https://github.com/mp911de/lettuce/wiki/Configuring-Client-resources) and log them somewhere in regular intervals to get a hint about congestion
2. You don't use transactions or blocking commands (`BLPOP`, …) so a single connection is perfectly fine. Redis itself is single-threaded so using more than one connection (per application instance) does not improve application performance. Also, a connection is assigned to one thread. Because of thread-affinity, using one connection but raising the pool size won't affect throughput.
3. If you run into a slow response scenario, it's easier to take a thread dump with `jstack` or something similar. Alternatively, plug in a monitoring tool and record latencies to correlate later snapshots of the threads.
4. I assume you won't see much because netty is event-driven and there's little work inside the handlers. If a read takes a long time, netty will read the available data from the buffer and then do nothing (event loop snooping) until further data arrives.

Which API are you using? Sync or async? If async, please be aware that future callbacks are processed on the NIO thread. If you perform heavy work in a callback, then this might be a source why netty is not able to proceed -> move to a dedicated executor.

**Comment by ameenhere** [comment]
I have enabled latency metrics with lettuce 3.5. Will try out some tests with the logs enabled and Yes, I am using a single connection (no connection pooling)
I will try to take thread dumps next time. I could see some "parked threads" around the lettuce redis calls when a thread dump was taken previously. Will post after doing some more analysis
From your answer, I understand that  lettuce library does not provide any methods to get the threadpool status.

My specific questions are
Q1. What do you think are the optimal values for ioThreadPoolSize/computationThreadPoolSize. I understand the default will be the number of cores (or whatever the runtime returns). Do you think raising the threadpool size to ,say 30, will make a difference in the performance?
Q2. Will there be a performance/latency improvement if I enable the non-ssl port and connect to it instead of the ssl port? Assuming the encryptions (or lack of) will make a difference?

**Comment by mp911de** [comment]
To your questions: It always depends, there's no simple answer.

1. Lettuce ships already with good defaults that initialize pools with the number of CPU cores. Regarding increasing the pool size: Rather set it to a small value, such as 3, if you work only with a single connection Redis Standalone connection.
2. It makes a difference because SSL adds computational and space overhead. I'd argue you won't notice the difference unless you're hitting scalability bounds (max out memory/cpu).

**Comment by ameenhere** [comment]
Thanks for your inputs. I agree with you. I was just wondering the use cases where increasing the ioThreadPoolSize/computationThreadPoolSize will make sense.
I guess you can close this then.

**Comment by mp911de** [comment]
Increasing pools sizes can make sense if you use Redis Cluster (or a lot of different standalone connections to independent Redis processes) and you want to benefit from high concurrency. In that case, you need the appropriate workloads and more cluster nodes than CPU cores on the app server. Anyhow, this is a rather special setup than common.

**Comment by michaelassraf** [comment]
Is there any way to control the shutdown behavior of the `LettuceFutures` pool? or to use my own underlying thread pool? I'm using the cluster mode.
