### ISSUE TITLE
All connections get RedisCommandTimeoutException until JVM restart

### ISSUE THREAD

**Issue by NoamB** [mp911de/lettuce#81]
Hi,
lettuce 3.1.Final
Java 8
Ubuntu trusty 14.04

I have a Clojure server running embedded Jetty9 and a RedisConnectionPool (maxIdle 5, maxActive 20), the redis being used as a session store, so it just sets and gets strings.
Redis is provided by AWS ElastiCache.

This has been running fine for weeks. Today I noticed that every request throws the exception below. Using redis-cli I could login to Redis without a prob and issue commands. After restarting my Java process, all is back to normal.

Not sure if this is already known and fixed in 3.2.Final or not.

```
com.lambdaworks.redis.RedisCommandTimeoutException: Command timed out
	at com.lambdaworks.redis.LettuceFutures.await(LettuceFutures.java:72) ~[dove-server-standalone-0.1.0-SNAPSHOT.jar:na]
	at com.lambdaworks.redis.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:59) ~[dove-server-standalone-0.1.0-SNAPSHOT.jar:na]
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87) ~[dove-server-standalone-0.1.0-SNAPSHOT.jar:na]
	at com.sun.proxy.$Proxy4.get(Unknown Source) ~[na:na]
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_20]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_20]
	at com.lambdaworks.redis.PooledConnectionInvocationHandler.handleInvocation(PooledConnectionInvocationHandler.java:47) ~[dove-server-standalone-0.1.0-SNAPSHOT.jar:na]
```

**Comment by mp911de** [comment]
Hi, 
this issue is a new report. In the early 3.0 betas there was an issue of race conditions when multiple threads try to dispatch commands on the same connection. The commands got in wrong order and were completed in a different order than redis sent answers. Your issue looks like a bit that way. 

Long-running servers are hard to debug. Can you check if you had any reconnects while your server was running? And if so, whether they happened today for the first time or not.

You actually do not need pooling, since all connections (sync, async) are thread-safe and redis operates mostly single-threaded. lettuce connections reconnect once the connection gets disconnected.

**Comment by NoamB** [comment]
Thanks for the quick response.
I do not see reconnection attempts, just on-demand failure.
I will update my server to latest version (3.2.Final) and will see if it happens again. Also will reduce the pool to a single connection as you advised.

**Comment by mp911de** [comment]
Do your logs hint at something that happened just before the timeouts occured?

**Comment by NoamB** [comment]
Not really, a user just tries to login, the server goes to Redis to pool the session and gets the exception.

**Comment by mp911de** [comment]
Do you have an update? lettuce 3.1 and lettuce 3.2 provide both the `reset()` method on the [RedisChannelWriter](http://redis.paluch.biz/docs/api/releases/3.1.Final/com/lambdaworks/redis/RedisChannelWriter.html). `reset` removes all buffered commands and clears out the response buffer. This *might* be helpful for certain use cases. You can obtain `RedisChannelWriter` from any async connection. Obtaining it from a sync connection is a bit trickier, since sync connections are proxies.

**Comment by NoamB** [comment]
I'm deploying 3.2.Final to 3 regions tonight, will let you know if anything interesting happens.

**Comment by mp911de** [comment]
Is this one still valid? Did you experience any issues?

**Comment by NoamB** [comment]
No issues so far, I will close it. If anything happens I will reopen...

**Comment by smaraja** [comment]
Hi, I using lettuce4.2 final , but still getting this exception. Can u help me?

**Comment by mp911de** [comment]
Timeout exceptions can have multiple reasons. Please open a new issue and attach your lettuce logs or a test case to reproduce the issue.
