### ISSUE TITLE
RedisClusterClient use transactions with multi and exec and discard not work

### ISSUE THREAD

**Issue by wanggit** [mp911de/lettuce#99]
hi
I get a RedisClusterAsyncConnection with RedisClusterClient.connectClusterAsync() method. but the transactions not work. code is below.
 ```java
List<RedisURI> initialUris = new ArrayList<RedisURI>();
initialUris.add(RedisURI.Builder.redis("192.168.2.120", 7000).build());
initialUris.add(RedisURI.Builder.redis("192.168.2.120", 7001).build());
initialUris.add(RedisURI.Builder.redis("192.168.2.120", 7002).build());
initialUris.add(RedisURI.Builder.redis("192.168.2.120", 7004).build());
RedisClusterClient rcc = new RedisClusterClient(initialUris);
RedisClusterAsyncConnection<String, String> conn = rcc.connectClusterAsync();
try {
	if( conn.multi().get().equals("OK") ){
		conn.set("city.name", "beijing");
		System.out.println( 1 / 0);
		conn.exec().get();
	}
} catch (Exception e) {
	conn.discard().get()
}
```
the code will occur exception, ```conn.exec().get()``` not run, ```conn.discard().get()``` is run. but the transaction commited. why?
please help me!1

**Comment by wanggit** [comment]
sorry. It's my fault; 
must watch some key before multi .

**Comment by mp911de** [comment]
Do not use `MULTI` with Redis Cluster using the global cluster connection, because it's not supported.

The key-less commands `MULTI`, `EXEC` and `DISCARD` cannot be routed to the appropriate nodes because:

1. There is no key with these commands
2. At the moment of invoking `MULTI`, the client does not know, which keys are going to be updated and therefore it's not possible right now to activate `MULTI` on a particular node
3. Cluster and `MULTI` in the way you use it, has a flavor of a distributed transaction

lettuce 3.3 will provide access to the particular connections to the cluster nodes. You can do transactions on the node connections since they are in the end like standalone connections.

One more thing: You use async connections in the code above, but you do not handle requests/responses in an async way. You can obtain a connection with a sync API by calling `RedisClusterClient#connectCluster`.

**Comment by wanggit** [comment]
Yes, I found below command worked good in redis-cli
```
WATCH {city:100}
MULTI
SET {city:100}.name beijing
SET {city:100}.code bj
DISCARD
```
But, It's not worked in Java client
```java
conn.watch("{city:100}");
conn.multi();
conn.set("{city:100}.name", "beijing");
conn.set("{city:100}.code", "bj");
System.out.println( 1 / 0);
conn.exec();
```
I waiting for lettuce 3.3, what time will be release?

**Comment by mp911de** [comment]
About end of August. The current 3.3-SNAPSHOT (https://oss.sonatype.org/content/repositories/snapshots/biz/paluch/redis/lettuce/3.3-SNAPSHOT/) contains already the functionality [RedisAdvancedClusterConnection.html#getConnection](http://redis.paluch.biz/docs/api/snapshots/3.3-SNAPSHOT/com/lambdaworks/redis/cluster/RedisAdvancedClusterConnection.html#getConnection-java.lang.String-), so you can take a look. Feedback appreciated.

**Comment by yiukalun** [comment]
The getConnection API was deprecated in Lettuce 4.

I am not sure how to perform multi() on clustered connection using Lettuce too.

Anyone can help?

**Comment by mp911de** [comment]
There's no multi support from a top-level cluster connection perspective because there are no distributed transactions in Redis. If you want to use transactions, then obtain a node-specific connection to the node that holds the keys you want to touch within the transaction (`StatefulRedisClusterConnection .getConnection(…)`).  

Please use StackOverflow or the mailing list if you have further questions.
